name: "Feature Request"
description: "Request a feature"
type: "Feature"
labels: ["priority: LOW"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking your time to help our plugin improve!
  - type: textarea
    id: description
    attributes:
      label: "Description of the feature"
      description: "Describe what you'd like added to the plugin."
    validations:
      required: true
  - type: dropdown
    id: plugin
    attributes:
      label: In which plugin would you like this feature?
      multiple: false
      options:
        - axafkzone
        - axauctions
        - axboosters
        - axcalendar
        - axenvoys
        - axgens
        - axgraves
        - axinventoryrestore
        - axkills
        - axkoth
        - axmines
        - axminions
        - axquestboard
        - axrankmenu
        - axrewards
        - axsellwands
        - axshulkers
        - axsmithing
        - axsumo
        - axtrade
        - axvaults
        - axplayerwarps
        - axdarkauctions
    validations:
      required: true        
  - type: checkboxes
    id: agreements
    attributes:
      label: "Agreements"
      description: "Please agree to some general guidelines"
      options:
        - label: "I have checked that this feature does not exist in the current latest version of the plugin available."
          required: true
        - label: "I accept that my feature request might not be added, and might be refused without any apparent reason."
          required: true
      
